const jerseyDef = {
    "global": {
        "palette": {
            "brown": "144 108 0",
            "black": "0 0 0",
            "blackMedium": "36 36 36",
            "darkBrown": "108 72 36",
            "flesh": "216 144 108",
            "flesh2": "216 144 108",
            "flesh3": "180 108 72",
            "flesh3bit": "216 144 108",
            "flesh3bit2": "180 108 72",
            "white": "252 252 252",
            "whiteMedium": "216 216 216",
        },
        "mapping": {
            "stick": "brown",
            "equipment": "black",
            "eyes": "darkBrown",
            "skin1": "flesh3bit",
            "skin2": "flesh3bit2",
            "skin3": "flesh3bit2",
            "skateBlade": "white"
        }
    },
    "3": {
        "name": "Chicago Blackhawks",
        "abbreviation": "CHI",
        "palette": {
            "red": "144 0 0",
            "yellow": "180 180 0",
            "brightRed": "180 0 0"
        },
        "jerseys": {
            "home": {
                "template": "classic",
                "helmet": "white",
                // "yolk1": "0 0 0",
                // "yolk2": "0 0 0",
                // "yolk3": "0 0 0",
                // "yolkCorner": "0 0 0",
                "shoulderPatch": "yellow",
                "jersey": "whiteMedium",
                "waist1": "red",
                "waist2": "whiteMedium",
                "waist3": "blackMedium",
                "pants": "blackMedium",
                "pantsStripe1": "white",
                "pantsStripe2": "red",
                // "socks": "0 0 0",
                "socksStripe1": "red",
                "socksStripe2": "blackMedium",
                // "armUpper": "0 0 0",
                "armStripe1": "red",
                "armStripe2": "whiteMedium",
                "armStripe3": "blackMedium",
                // "forearm": "0 0 0",
                "goalieMask": "white",
                "crest": [
                    "white",   "black", "black", "black",     "white",
                    "white",   "brown", "black", "black",     "brightRed",
                    "brown",   "brown", "brown", "brightRed", "yellow",
                    "white",   "brown", "black", "brown",     "white",
                ]
            },
            "away": {
                "template": "classic",
                "helmet": "blackMedium",
                // "yolk1": "0 0 0",
                // "yolk2": "0 0 0",
                // "yolk3": "0 0 0",
                // "yolkCorner": "0 0 0",
                "shoulderPatch": "yellow",
                "jersey": "red",
                "waist1": "whiteMedium",
                "waist2": "blackMedium",
                "waist3": "whiteMedium",
                "pants": "blackMedium",
                "pantsStripe1": "white",
                "pantsStripe2": "red",
                // "socks": "0 0 0",
                "socksStripe1": "whiteMedium",
                "socksStripe2": "blackMedium",
                // "armUpper": "0 0 0",
                "armStripe1": "whiteMedium",
                "armStripe2": "blackMedium",
                "armStripe3": "whiteMedium",
                // "forearm": "0 0 0",
                "goalieMask": "white",
                "crest": [
                    "red",   "black", "black", "black",     "red",
                    "red",   "brown", "black", "black",     "brightRed",
                    "brown", "brown", "brown", "brightRed", "yellow",
                    "red",   "brown", "black", "brown",     "red",
                ]
            }
        } 
    }
}

const homePals = [ 
    { name: 'BOS', template: 'universal'}, 
    { name: 'BUF', template: 'universal'}, 
    { name: 'CGY', template: 'universal'}, 
    { name: 'CHI', template: 'universal'}, 
    { name: 'DET', template: 'universal'}, 
    { name: 'EDM', template: 'universal'}, 
    { name: 'HFD', template: 'universal'}, 
    { name: 'LA', template: 'universal'}, 
    { name: 'DAL', template: 'longArms'}, 
    { name: 'MTL', template: 'universal'}, 
    { name: 'NJ', template: 'universal'}, 
    { name: 'NYI', template: 'universal'}, 
    { name: 'NYR', template: 'universal'}, 
    { name: 'OTT', template: 'universal'}, 
    { name: 'PHI', template: 'armSwoop'}, 
    { name: 'PIT', template: 'universal'}, 
    { name: 'QUE', template: 'waistDots'}, 
    { name: 'STL', template: 'universal'}, 
    { name: 'SJ', template: 'universal'}, 
    { name: 'TB', template: 'universal'}, 
    { name: 'TOR', template: 'universal'}, 
    { name: 'VAN', template: 'universal'}, 
    { name: 'WSH', template: 'longArms'}, 
    { name: 'WPG', template: 'universal'}, 
    { name: 'ANA', template: 'vArm'}, 
    { name: 'FLA', template: 'aArm'}, 
    { name: 'ASW', template: 'star'}, 
    { name: 'ASE', template: 'star'}, 
];

const awayPals = [ 
    { name: 'BOS', template: 'universal'}, 
    { name: 'BUF', template: 'universal'}, 
    { name: 'CGY', template: 'universal'}, 
    { name: 'CHI', template: 'universal'}, 
    { name: 'DET', template: 'universal'}, 
    { name: 'EDM', template: 'universal'}, 
    { name: 'HFD', template: 'universal'}, 
    { name: 'LA', template: 'universal'}, 
    { name: 'DAL', template: 'universal'}, 
    { name: 'MTL', template: 'universal'}, 
    { name: 'NJ', template: 'universal'}, 
    { name: 'NYI', template: 'universal'}, 
    { name: 'NYR', template: 'universal'}, 
    { name: 'OTT', template: 'universal'}, 
    { name: 'PHI', template: 'armSwoop'}, 
    { name: 'PIT', template: 'universal'}, 
    { name: 'QUE', template: 'waistDots'}, 
    { name: 'STL', template: 'universal'}, 
    { name: 'SJ', template: 'universal'}, 
    { name: 'TB', template: 'universal'}, 
    { name: 'TOR', template: 'universal'}, 
    { name: 'VAN', template: 'universal'}, 
    { name: 'WSH', template: 'longArms'}, 
    { name: 'WPG', template: 'universal'}, 
    { name: 'ANA', template: 'vArm'}, 
    { name: 'FLA', template: 'aArm'}, 
    { name: 'ASW', template: 'star'}, 
    { name: 'ASE', template: 'star'}, 
];

module.exports = jerseyDef;