const global = {
    "palette": {
        "brown": "144 108 0",
        "black": "0 0 0",
        "blackMedium": "36 36 36",
        "darkBrown": "108 72 36",
        "flesh": "216 144 108",
        "flesh2": "216 144 108",
        "flesh3": "180 108 72",
        "flesh3bit": "216 144 108",
        "flesh3bit2": "180 108 72",
        "white": "252 252 252",
        "whiteMedium": "216 216 216",
    },
    "mapping": {
        "stick": "brown",
        "equipment": "black",
        "eyes": "darkBrown",
        "skin1": "flesh3bit",
        "skin2": "flesh3bit2",
        "skin3": "flesh3bit2",
        "skateBlade": "white"
    }
};

const homePals = [ 
    { name: 'BOS', template: 'universal'}, 
    { name: 'BUF', template: 'universal'}, 
    { name: 'CGY', template: 'universal'}, 
    { name: 'CHI', template: 'universal'}, 
    { name: 'DET', template: 'universal'}, 
    { name: 'EDM', template: 'universal'}, 
    { name: 'HFD', template: 'universal'}, 
    { name: 'LA', template: 'universal'}, 
    { name: 'DAL', template: 'longArms'}, 
    { name: 'MTL', template: 'universal'}, 
    { name: 'NJ', template: 'universal'}, 
    { name: 'NYI', template: 'universal'}, 
    { name: 'NYR', template: 'universal'}, 
    { name: 'OTT', template: 'universal'}, 
    { name: 'PHI', template: 'armSwoop'}, 
    { name: 'PIT', template: 'universal'}, 
    { name: 'QUE', template: 'waistDots'}, 
    { name: 'STL', template: 'universal'}, 
    { name: 'SJ', template: 'universal'}, 
    { name: 'TB', template: 'universal'}, 
    { name: 'TOR', template: 'universal'}, 
    { name: 'VAN', template: 'universal'}, 
    { name: 'WSH', template: 'armDots'}, 
    { name: 'WPG', template: 'universal'}, 
    { name: 'ANA', template: 'vArm'}, 
    { name: 'FLA', template: 'aArm'}, 
    { name: 'ASW', template: 'star'}, 
    { name: 'ASE', template: 'star'}, 
];

const awayPals = [ 
    { name: 'BOS', template: 'universal'}, 
    { name: 'BUF', template: 'universal'}, 
    { name: 'CGY', template: 'universal'}, 
    { name: 'CHI', template: 'universal'}, 
    { name: 'DET', template: 'universal'}, 
    { name: 'EDM', template: 'universal'}, 
    { name: 'HFD', template: 'universal'}, 
    { name: 'LA', template: 'universal'}, 
    { name: 'DAL', template: 'universal'}, 
    { name: 'MTL', template: 'universal'}, 
    { name: 'NJ', template: 'universal'}, 
    { name: 'NYI', template: 'universal'}, 
    { name: 'NYR', template: 'universal'}, 
    { name: 'OTT', template: 'universal'}, 
    { name: 'PHI', template: 'armSwoop'}, 
    { name: 'PIT', template: 'universal'}, 
    { name: 'QUE', template: 'waistDots'}, 
    { name: 'STL', template: 'universal'}, 
    { name: 'SJ', template: 'universal'}, 
    { name: 'TB', template: 'universal'}, 
    { name: 'TOR', template: 'universal'}, 
    { name: 'VAN', template: 'universal'}, 
    { name: 'WSH', template: 'armDots'}, 
    { name: 'WPG', template: 'universal'}, 
    { name: 'ANA', template: 'vArm'}, 
    { name: 'FLA', template: 'aArm'}, 
    { name: 'ASW', template: 'star'}, 
    { name: 'ASE', template: 'star'}, 
];

module.exports = [global, homePals, awayP];